# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
my_dBCPEo <- function(x, mu, sigma, nu, tau, log_ = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_dBCPEo', PACKAGE = 'IMPACTncdEngl', x, mu, sigma, nu, tau, log_, n_cpu)
}

#' @export
my_pBCPEo <- function(q, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_pBCPEo', PACKAGE = 'IMPACTncdEngl', q, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_qBCPEo <- function(p, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_qBCPEo', PACKAGE = 'IMPACTncdEngl', p, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_dBCT <- function(x, mu, sigma, nu, tau, log_ = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_dBCT', PACKAGE = 'IMPACTncdEngl', x, mu, sigma, nu, tau, log_, n_cpu)
}

#' @export
my_pBCT <- function(q, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_pBCT', PACKAGE = 'IMPACTncdEngl', q, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_qBCT <- function(p, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_qBCT', PACKAGE = 'IMPACTncdEngl', p, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_dBNB <- function(x, mu, sigma, nu, log = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_dBNB', PACKAGE = 'IMPACTncdEngl', x, mu, sigma, nu, log, n_cpu)
}

#' @export
my_pBNB <- function(q, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_pBNB', PACKAGE = 'IMPACTncdEngl', q, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_qBNB <- function(p, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_qBNB', PACKAGE = 'IMPACTncdEngl', p, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_qZIBNB <- function(p, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_qZIBNB', PACKAGE = 'IMPACTncdEngl', p, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_qZABNB <- function(p, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_qZABNB', PACKAGE = 'IMPACTncdEngl', p, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_dDEL <- function(x, mu, sigma, nu, log_ = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_dDEL', PACKAGE = 'IMPACTncdEngl', x, mu, sigma, nu, log_, n_cpu)
}

#' @export
my_pDEL <- function(q, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_pDEL', PACKAGE = 'IMPACTncdEngl', q, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_qDEL <- function(p, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_qDEL', PACKAGE = 'IMPACTncdEngl', p, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_get_C <- function(x, mu, sigma) {
    .Call('_IMPACTncdEngl_my_get_C', PACKAGE = 'IMPACTncdEngl', x, mu, sigma)
}

#' @export
my_dDPO <- function(x, mu, sigma, log_ = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_dDPO', PACKAGE = 'IMPACTncdEngl', x, mu, sigma, log_, n_cpu)
}

#' @export
my_pDPO <- function(q, mu, sigma, lower_tail = TRUE, log_p = FALSE) {
    .Call('_IMPACTncdEngl_my_pDPO', PACKAGE = 'IMPACTncdEngl', q, mu, sigma, lower_tail, log_p)
}

#' @export
my_qDPO <- function(p, mu, sigma, lower_tail = TRUE, log_p = FALSE, max_value = 0L, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_qDPO', PACKAGE = 'IMPACTncdEngl', p, mu, sigma, lower_tail, log_p, max_value, n_cpu)
}

#' @export
simcpp <- function(dt, l, mc) {
    invisible(.Call('_IMPACTncdEngl_simcpp', PACKAGE = 'IMPACTncdEngl', dt, l, mc))
}

#' @export
my_qMN4 <- function(p, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_qMN4', PACKAGE = 'IMPACTncdEngl', p, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_dNBI <- function(x, mu, sigma, log_p, n_cpu) {
    .Call('_IMPACTncdEngl_my_dNBI', PACKAGE = 'IMPACTncdEngl', x, mu, sigma, log_p, n_cpu)
}

#' @export
my_pNBI <- function(q, mu, sigma, lower_tail, log_p, n_cpu) {
    .Call('_IMPACTncdEngl_my_pNBI', PACKAGE = 'IMPACTncdEngl', q, mu, sigma, lower_tail, log_p, n_cpu)
}

#' @export
my_qNBI <- function(p, mu, sigma, lower_tail, log_p, n_cpu) {
    .Call('_IMPACTncdEngl_my_qNBI', PACKAGE = 'IMPACTncdEngl', p, mu, sigma, lower_tail, log_p, n_cpu)
}

#' @export
my_qZANBI <- function(p, mu, sigma, nu, lower_tail, log_p, n_cpu) {
    .Call('_IMPACTncdEngl_my_qZANBI', PACKAGE = 'IMPACTncdEngl', p, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_pZANBI_scalar <- function(q, mu, sigma, nu, lower_tail, log_p, check) {
    .Call('_IMPACTncdEngl_my_pZANBI_scalar', PACKAGE = 'IMPACTncdEngl', q, mu, sigma, nu, lower_tail, log_p, check)
}

#' @export
my_dSICHEL <- function(x, mu, sigma, nu, log_ = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_dSICHEL', PACKAGE = 'IMPACTncdEngl', x, mu, sigma, nu, log_, n_cpu)
}

#' @export
my_pSICHEL <- function(q, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_pSICHEL', PACKAGE = 'IMPACTncdEngl', q, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_qSICHEL <- function(p, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_qSICHEL', PACKAGE = 'IMPACTncdEngl', p, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_qZISICHEL <- function(p, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_qZISICHEL', PACKAGE = 'IMPACTncdEngl', p, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_pZISICHEL <- function(q, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_IMPACTncdEngl_my_pZISICHEL', PACKAGE = 'IMPACTncdEngl', q, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
carry_forward <- function(x, pid_mrk, y, byref) {
    .Call('_IMPACTncdEngl_carry_forward', PACKAGE = 'IMPACTncdEngl', x, pid_mrk, y, byref)
}

#' @export
carry_forward_incr <- function(x, pid_mrk, recur, y, byref) {
    .Call('_IMPACTncdEngl_carry_forward_incr', PACKAGE = 'IMPACTncdEngl', x, pid_mrk, recur, y, byref)
}

#' @export
carry_backward <- function(x, pid_mrk, y) {
    .Call('_IMPACTncdEngl_carry_backward', PACKAGE = 'IMPACTncdEngl', x, pid_mrk, y)
}

#' @export
carry_backward_decr <- function(x, pid_mrk) {
    .Call('_IMPACTncdEngl_carry_backward_decr', PACKAGE = 'IMPACTncdEngl', x, pid_mrk)
}

#' @export
mk_new_simulant_markers <- function(pid) {
    .Call('_IMPACTncdEngl_mk_new_simulant_markers', PACKAGE = 'IMPACTncdEngl', pid)
}

#' @export
identify_longdead <- function(x, pid) {
    .Call('_IMPACTncdEngl_identify_longdead', PACKAGE = 'IMPACTncdEngl', x, pid)
}

#' @export
identify_invitees <- function(elig, prev_inv, prb, freq, pid) {
    .Call('_IMPACTncdEngl_identify_invitees', PACKAGE = 'IMPACTncdEngl', elig, prev_inv, prb, freq, pid)
}

#' @export
hc_effect <- function(x, prb_of_continuation, pid) {
    .Call('_IMPACTncdEngl_hc_effect', PACKAGE = 'IMPACTncdEngl', x, prb_of_continuation, pid)
}

#' @export
fbound <- function(x, a, b) {
    .Call('_IMPACTncdEngl_fbound', PACKAGE = 'IMPACTncdEngl', x, a, b)
}

#' @export
antilogit <- function(x) {
    .Call('_IMPACTncdEngl_antilogit', PACKAGE = 'IMPACTncdEngl', x)
}

dtsubset <- function(x, rows, cols) {
    .Call('_IMPACTncdEngl_dtsubset', PACKAGE = 'IMPACTncdEngl', x, rows, cols)
}

#' @export
fscramble_trajectories <- function(x, pid, jumpiness = 1.0, inplace = TRUE) {
    .Call('_IMPACTncdEngl_fscramble_trajectories', PACKAGE = 'IMPACTncdEngl', x, pid, jumpiness, inplace)
}

#' @export
shift_bypidNum <- function(x, lag, replace, id) {
    .Call('_IMPACTncdEngl_shift_bypidNum', PACKAGE = 'IMPACTncdEngl', x, lag, replace, id)
}

#' @export
shift_bypidInt <- function(x, lag, replace, id) {
    .Call('_IMPACTncdEngl_shift_bypidInt', PACKAGE = 'IMPACTncdEngl', x, lag, replace, id)
}

#' @export
shift_bypidBool <- function(x, lag, replace, id) {
    .Call('_IMPACTncdEngl_shift_bypidBool', PACKAGE = 'IMPACTncdEngl', x, lag, replace, id)
}

#' @export
shift_bypidStr <- function(x, lag, replace, id) {
    .Call('_IMPACTncdEngl_shift_bypidStr', PACKAGE = 'IMPACTncdEngl', x, lag, replace, id)
}

#' @export
simsmok <- function(df, pr_relapse, relapse_cutoff) {
    invisible(.Call('_IMPACTncdEngl_simsmok', PACKAGE = 'IMPACTncdEngl', df, pr_relapse, relapse_cutoff))
}

#' @export
simsmok_sc <- function(df, pr_relapse, relapse_cutoff, row_sel) {
    invisible(.Call('_IMPACTncdEngl_simsmok_sc', PACKAGE = 'IMPACTncdEngl', df, pr_relapse, relapse_cutoff, row_sel))
}

#' @export
simsmok_postcalibration <- function(df) {
    invisible(.Call('_IMPACTncdEngl_simsmok_postcalibration', PACKAGE = 'IMPACTncdEngl', df))
}

#' @export
simsmok_cig <- function(df) {
    invisible(.Call('_IMPACTncdEngl_simsmok_cig', PACKAGE = 'IMPACTncdEngl', df))
}

#' @export
simsmok_cig_sc <- function(df, row_sel) {
    invisible(.Call('_IMPACTncdEngl_simsmok_cig_sc', PACKAGE = 'IMPACTncdEngl', df, row_sel))
}

#' @export
simsmok_complete_cessation_cig <- function(df) {
    invisible(.Call('_IMPACTncdEngl_simsmok_complete_cessation_cig', PACKAGE = 'IMPACTncdEngl', df))
}

#' @export
simsmok_cessation <- function(smok_status, smok_quit_yrs, smok_dur, sex, qimd, new_pid, hc_eff, relapse_rn, pr_relapse, relapse_cutoff) {
    .Call('_IMPACTncdEngl_simsmok_cessation', PACKAGE = 'IMPACTncdEngl', smok_status, smok_quit_yrs, smok_dur, sex, qimd, new_pid, hc_eff, relapse_rn, pr_relapse, relapse_cutoff)
}

#' @export
simsmok_complete_cessation <- function(smok_status, smok_quit_yrs, smok_dur, new_pid, year, policy_first_year) {
    .Call('_IMPACTncdEngl_simsmok_complete_cessation', PACKAGE = 'IMPACTncdEngl', smok_status, smok_quit_yrs, smok_dur, new_pid, year, policy_first_year)
}

#' @export
simsmok_policy_impact_incr <- function(smok_status, smok_quit_yrs, smok_dur, new_pid, hc_eff) {
    .Call('_IMPACTncdEngl_simsmok_policy_impact_incr', PACKAGE = 'IMPACTncdEngl', smok_status, smok_quit_yrs, smok_dur, new_pid, hc_eff)
}

#' @export
simsmok_policy_impact_decr <- function(smok_status, smok_quit_yrs, smok_dur, smok_cig, new_pid, hc_eff) {
    .Call('_IMPACTncdEngl_simsmok_policy_impact_decr', PACKAGE = 'IMPACTncdEngl', smok_status, smok_quit_yrs, smok_dur, smok_cig, new_pid, hc_eff)
}

#' @export
wtd_ADstat <- function(a, wa, b, wb) {
    .Call('_IMPACTncdEngl_wtd_ADstat', PACKAGE = 'IMPACTncdEngl', a, wa, b, wb)
}

#' @export
wtd_KSstat <- function(a, wa, b, wb) {
    .Call('_IMPACTncdEngl_wtd_KSstat', PACKAGE = 'IMPACTncdEngl', a, wa, b, wb)
}

