---
title: "Installing R on Linux"
author: "Dr. Chris Kypridemos, Dr. Anna Head, Adithi R. Upadhya"
date: "11 March, 2024"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Installing R on Linux}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


- The installation procedure outlined here pertains to versions R 4.3.2. 

- The installation process for R has exhibited notable consistency throughout the years.

### Steps to install R on Linux

1. We need to first install R navigate to [CRAN](https://cran.r-project.org/). Select a mirror site near you; a list of [CRAN mirrors](https://cran.r-project.org/mirrors.html) appears at the upper left of the CRAN home page.

2. Click **Download R for Linux (Debian, Fedora/Redhat, Ubuntu)**. We suggest that you use the [0-Cloud mirror](https://cloud.r-project.org/), which is the first on the list. Click on the link **Download R for Linux**, which appears near the top of the page. R is available for several Linux distributions (Debian, RedHat, SUSE, and Ubuntu); select your distribution, and proceed as directed.

3. If you have a Linux or Unix system that's not compatible with one of these distributions, you will have to compile R from source code; the [procedure](https://cran.r-project.org/doc/FAQ/R-FAQ.html#How-can-R-be-installed-_0028Unix_002dlike_0029) for doing so is described in the R FAQ (frequently asked questions) list.

