// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simcpp
void simcpp(DataFrame dt, const List l, const int mc);
RcppExport SEXP _IMPACTncdEngland_simcpp(SEXP dtSEXP, SEXP lSEXP, SEXP mcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< const List >::type l(lSEXP);
    Rcpp::traits::input_parameter< const int >::type mc(mcSEXP);
    simcpp(dt, l, mc);
    return R_NilValue;
END_RCPP
}
// simcpp_year_based
void simcpp_year_based(DataFrame dt, const List l, const int mc);
RcppExport SEXP _IMPACTncdEngland_simcpp_year_based(SEXP dtSEXP, SEXP lSEXP, SEXP mcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< const List >::type l(lSEXP);
    Rcpp::traits::input_parameter< const int >::type mc(mcSEXP);
    simcpp_year_based(dt, l, mc);
    return R_NilValue;
END_RCPP
}
// simsmok
void simsmok(DataFrame& df, const NumericMatrix& pr_relapse, const int& relapse_cutoff);
RcppExport SEXP _IMPACTncdEngland_simsmok(SEXP dfSEXP, SEXP pr_relapseSEXP, SEXP relapse_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type pr_relapse(pr_relapseSEXP);
    Rcpp::traits::input_parameter< const int& >::type relapse_cutoff(relapse_cutoffSEXP);
    simsmok(df, pr_relapse, relapse_cutoff);
    return R_NilValue;
END_RCPP
}
// simsmok_sc
void simsmok_sc(DataFrame& df, const NumericMatrix& pr_relapse, const int& relapse_cutoff, const IntegerVector& row_sel);
RcppExport SEXP _IMPACTncdEngland_simsmok_sc(SEXP dfSEXP, SEXP pr_relapseSEXP, SEXP relapse_cutoffSEXP, SEXP row_selSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type pr_relapse(pr_relapseSEXP);
    Rcpp::traits::input_parameter< const int& >::type relapse_cutoff(relapse_cutoffSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type row_sel(row_selSEXP);
    simsmok_sc(df, pr_relapse, relapse_cutoff, row_sel);
    return R_NilValue;
END_RCPP
}
// simsmok_postcalibration
void simsmok_postcalibration(DataFrame& df);
RcppExport SEXP _IMPACTncdEngland_simsmok_postcalibration(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame& >::type df(dfSEXP);
    simsmok_postcalibration(df);
    return R_NilValue;
END_RCPP
}
// simsmok_cig
void simsmok_cig(DataFrame& df);
RcppExport SEXP _IMPACTncdEngland_simsmok_cig(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame& >::type df(dfSEXP);
    simsmok_cig(df);
    return R_NilValue;
END_RCPP
}
// simsmok_cig_sc
void simsmok_cig_sc(DataFrame& df, const IntegerVector& row_sel);
RcppExport SEXP _IMPACTncdEngland_simsmok_cig_sc(SEXP dfSEXP, SEXP row_selSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type row_sel(row_selSEXP);
    simsmok_cig_sc(df, row_sel);
    return R_NilValue;
END_RCPP
}
// simsmok_complete_cessation_cig
void simsmok_complete_cessation_cig(DataFrame& df);
RcppExport SEXP _IMPACTncdEngland_simsmok_complete_cessation_cig(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame& >::type df(dfSEXP);
    simsmok_complete_cessation_cig(df);
    return R_NilValue;
END_RCPP
}
// simsmok_cessation
List simsmok_cessation(const IntegerVector& smok_status, const IntegerVector& smok_quit_yrs, const IntegerVector& smok_dur, const IntegerVector& sex, const IntegerVector& qimd, const LogicalVector& new_pid, const IntegerVector& hc_eff, const NumericVector& relapse_rn, const NumericMatrix& pr_relapse, const int& relapse_cutoff);
RcppExport SEXP _IMPACTncdEngland_simsmok_cessation(SEXP smok_statusSEXP, SEXP smok_quit_yrsSEXP, SEXP smok_durSEXP, SEXP sexSEXP, SEXP qimdSEXP, SEXP new_pidSEXP, SEXP hc_effSEXP, SEXP relapse_rnSEXP, SEXP pr_relapseSEXP, SEXP relapse_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type smok_status(smok_statusSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type smok_quit_yrs(smok_quit_yrsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type smok_dur(smok_durSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type sex(sexSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type qimd(qimdSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type new_pid(new_pidSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type hc_eff(hc_effSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type relapse_rn(relapse_rnSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type pr_relapse(pr_relapseSEXP);
    Rcpp::traits::input_parameter< const int& >::type relapse_cutoff(relapse_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(simsmok_cessation(smok_status, smok_quit_yrs, smok_dur, sex, qimd, new_pid, hc_eff, relapse_rn, pr_relapse, relapse_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// simsmok_complete_cessation
List simsmok_complete_cessation(const IntegerVector& smok_status, const IntegerVector& smok_quit_yrs, const IntegerVector& smok_dur, const LogicalVector& new_pid, const IntegerVector& year, const int policy_first_year);
RcppExport SEXP _IMPACTncdEngland_simsmok_complete_cessation(SEXP smok_statusSEXP, SEXP smok_quit_yrsSEXP, SEXP smok_durSEXP, SEXP new_pidSEXP, SEXP yearSEXP, SEXP policy_first_yearSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type smok_status(smok_statusSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type smok_quit_yrs(smok_quit_yrsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type smok_dur(smok_durSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type new_pid(new_pidSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type year(yearSEXP);
    Rcpp::traits::input_parameter< const int >::type policy_first_year(policy_first_yearSEXP);
    rcpp_result_gen = Rcpp::wrap(simsmok_complete_cessation(smok_status, smok_quit_yrs, smok_dur, new_pid, year, policy_first_year));
    return rcpp_result_gen;
END_RCPP
}
// simsmok_policy_impact_incr
List simsmok_policy_impact_incr(const IntegerVector& smok_status, const IntegerVector& smok_quit_yrs, const IntegerVector& smok_dur, const LogicalVector& new_pid, const IntegerVector& hc_eff);
RcppExport SEXP _IMPACTncdEngland_simsmok_policy_impact_incr(SEXP smok_statusSEXP, SEXP smok_quit_yrsSEXP, SEXP smok_durSEXP, SEXP new_pidSEXP, SEXP hc_effSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type smok_status(smok_statusSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type smok_quit_yrs(smok_quit_yrsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type smok_dur(smok_durSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type new_pid(new_pidSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type hc_eff(hc_effSEXP);
    rcpp_result_gen = Rcpp::wrap(simsmok_policy_impact_incr(smok_status, smok_quit_yrs, smok_dur, new_pid, hc_eff));
    return rcpp_result_gen;
END_RCPP
}
// simsmok_policy_impact_decr
List simsmok_policy_impact_decr(const IntegerVector& smok_status, const IntegerVector& smok_quit_yrs, const IntegerVector& smok_dur, const IntegerVector& smok_cig, const LogicalVector& new_pid, const IntegerVector& hc_eff);
RcppExport SEXP _IMPACTncdEngland_simsmok_policy_impact_decr(SEXP smok_statusSEXP, SEXP smok_quit_yrsSEXP, SEXP smok_durSEXP, SEXP smok_cigSEXP, SEXP new_pidSEXP, SEXP hc_effSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type smok_status(smok_statusSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type smok_quit_yrs(smok_quit_yrsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type smok_dur(smok_durSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type smok_cig(smok_cigSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type new_pid(new_pidSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type hc_eff(hc_effSEXP);
    rcpp_result_gen = Rcpp::wrap(simsmok_policy_impact_decr(smok_status, smok_quit_yrs, smok_dur, smok_cig, new_pid, hc_eff));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IMPACTncdEngland_simcpp", (DL_FUNC) &_IMPACTncdEngland_simcpp, 3},
    {"_IMPACTncdEngland_simcpp_year_based", (DL_FUNC) &_IMPACTncdEngland_simcpp_year_based, 3},
    {"_IMPACTncdEngland_simsmok", (DL_FUNC) &_IMPACTncdEngland_simsmok, 3},
    {"_IMPACTncdEngland_simsmok_sc", (DL_FUNC) &_IMPACTncdEngland_simsmok_sc, 4},
    {"_IMPACTncdEngland_simsmok_postcalibration", (DL_FUNC) &_IMPACTncdEngland_simsmok_postcalibration, 1},
    {"_IMPACTncdEngland_simsmok_cig", (DL_FUNC) &_IMPACTncdEngland_simsmok_cig, 1},
    {"_IMPACTncdEngland_simsmok_cig_sc", (DL_FUNC) &_IMPACTncdEngland_simsmok_cig_sc, 2},
    {"_IMPACTncdEngland_simsmok_complete_cessation_cig", (DL_FUNC) &_IMPACTncdEngland_simsmok_complete_cessation_cig, 1},
    {"_IMPACTncdEngland_simsmok_cessation", (DL_FUNC) &_IMPACTncdEngland_simsmok_cessation, 10},
    {"_IMPACTncdEngland_simsmok_complete_cessation", (DL_FUNC) &_IMPACTncdEngland_simsmok_complete_cessation, 6},
    {"_IMPACTncdEngland_simsmok_policy_impact_incr", (DL_FUNC) &_IMPACTncdEngland_simsmok_policy_impact_incr, 5},
    {"_IMPACTncdEngland_simsmok_policy_impact_decr", (DL_FUNC) &_IMPACTncdEngland_simsmok_policy_impact_decr, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_IMPACTncdEngland(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
